server:
  port: 8068

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?useSSL=false
    username: root
    password: 'root'
    tomcat:
      validation-query: select 1
      test-on-return: true
      test-on-borrow: true
      test-while-idle: true
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: true

  redis:
    host: localhost
    port: 6379
    database: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
